name: Deploy
'on': push
jobs:
  my-job: null
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Instal NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Dependencies
      run: npm ci
    - name: Test
      run: npm run test
    - name: Build
      run: npm build
    - name: Deploy
      run: echo "Deploying..."
