name: Output Issue

on:
  push:
    branches:
      - main

jobs:
  my-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Output Issue
        run: echo "${{ toJSON(issue) }}"
        run: echo "${{ toJSON(github) }}"
